/**
 * College Basketball Team Logos
 * Using ESPN CDN for team logos (numeric IDs)
 */

export const getCBBTeamLogo = (teamName) => {
  const teamLogos = {
    // ACC
    'Duke': 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
    'Duke Blue Devils': 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
    'North Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
    'North Carolina Tar Heels': 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
    'UNC': 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
    'Virginia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
    'Virginia Cavaliers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
    'Virginia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
    'Virginia Tech Hokies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
    'Syracuse': 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
    'Syracuse Orange': 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
    'Louisville': 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
    'Louisville Cardinals': 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
    'Florida State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
    'Florida State Seminoles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
    'Clemson': 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
    'Clemson Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
    'Wake Forest': 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
    'Wake Forest Demon Deacons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
    'Pittsburgh': 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
    'Pittsburgh Panthers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
    'Georgia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
    'Georgia Tech Yellow Jackets': 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
    'Boston College': 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
    'Boston College Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
    'NC State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
    'NC State Wolfpack': 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
    'Notre Dame': 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
    'Notre Dame Fighting Irish': 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
    'Miami': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
    'Miami Hurricanes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
    'Stanford': 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
    'Stanford Cardinal': 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
    'California': 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png',
    'California Golden Bears': 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png',

    // Big Ten
    'Michigan State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
    'Michigan State Spartans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
    'Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
    'Michigan Wolverines': 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
    'Ohio State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
    'Ohio State Buckeyes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
    'Purdue': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
    'Purdue Boilermakers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
    'Illinois': 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
    'Illinois Fighting Illini': 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
    'Indiana': 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
    'Indiana Hoosiers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
    'Wisconsin': 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
    'Wisconsin Badgers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
    'Iowa': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
    'Iowa Hawkeyes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
    'Maryland': 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
    'Maryland Terrapins': 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
    'Penn State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
    'Penn State Nittany Lions': 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
    'Minnesota': 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
    'Minnesota Golden Gophers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
    'Northwestern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
    'Northwestern Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
    'Nebraska': 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
    'Nebraska Cornhuskers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
    'Rutgers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
    'Rutgers Scarlet Knights': 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
    'UCLA': 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
    'UCLA Bruins': 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
    'USC': 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
    'USC Trojans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
    'Washington': 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png',
    'Washington Huskies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png',
    'Oregon': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',
    'Oregon Ducks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',

    // Big 12
    'Kansas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
    'Kansas Jayhawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
    'Kansas State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
    'Kansas State Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
    'Baylor': 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
    'Baylor Bears': 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
    'Texas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
    'Texas Longhorns': 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
    'Texas Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
    'Texas Tech Red Raiders': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
    'Iowa State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
    'Iowa State Cyclones': 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
    'Oklahoma State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
    'Oklahoma State Cowboys': 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
    'West Virginia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
    'West Virginia Mountaineers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
    'TCU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
    'TCU Horned Frogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
    'Houston': 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
    'Houston Cougars': 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
    'Cincinnati': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
    'Cincinnati Bearcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
    'UCF': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
    'UCF Knights': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
    'BYU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
    'BYU Cougars': 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
    'Colorado': 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
    'Colorado Buffaloes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
    'Utah': 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
    'Utah Utes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
    'Arizona': 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
    'Arizona Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
    'Arizona State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
    'Arizona State Sun Devils': 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png',

    // SEC
    'Kentucky': 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
    'Kentucky Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
    'Tennessee': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
    'Tennessee Volunteers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
    'Alabama': 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
    'Alabama Crimson Tide': 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
    'Auburn': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
    'Auburn Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
    'Arkansas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
    'Arkansas Razorbacks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
    'Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
    'Florida Gators': 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
    'Georgia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
    'Georgia Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
    'LSU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
    'LSU Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
    'Missouri': 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
    'Missouri Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
    'Ole Miss': 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
    'Ole Miss Rebels': 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
    'Mississippi State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
    'Mississippi State Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
    'South Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png',
    'South Carolina Gamecocks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png',
    'Texas A&M': 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
    'Texas A&M Aggies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
    'Vanderbilt': 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
    'Vanderbilt Commodores': 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
    'Oklahoma': 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
    'Oklahoma Sooners': 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png',

    // Big East
    'UConn': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'UConn Huskies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'Connecticut': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'Connecticut Huskies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'Villanova': 'https://a.espncdn.com/i/teamlogos/ncaa/500/222.png',
    'Villanova Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/222.png',
    'Marquette': 'https://a.espncdn.com/i/teamlogos/ncaa/500/269.png',
    'Marquette Golden Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/269.png',
    'Creighton': 'https://a.espncdn.com/i/teamlogos/ncaa/500/156.png',
    'Creighton Bluejays': 'https://a.espncdn.com/i/teamlogos/ncaa/500/156.png',
    'Xavier': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png',
    'Xavier Musketeers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png',
    'Seton Hall': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png',
    'Seton Hall Pirates': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png',
    'Providence': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png',
    'Providence Friars': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2507.png',
    'Georgetown': 'https://a.espncdn.com/i/teamlogos/ncaa/500/46.png',
    'Georgetown Hoyas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/46.png',
    'Butler': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png',
    'Butler Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2086.png',
    "St. John's": 'https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png',
    "St. John's Red Storm": 'https://a.espncdn.com/i/teamlogos/ncaa/500/2599.png',
    'DePaul': 'https://a.espncdn.com/i/teamlogos/ncaa/500/305.png',
    'DePaul Blue Demons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/305.png',

    // Atlantic 10 / Mid-Majors
    'Dayton': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png',
    'Dayton Flyers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2168.png',
    'Davidson': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2166.png',
    'Davidson Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2166.png',
    'VCU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png',
    'VCU Rams': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png',
    'George Mason': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png',
    'George Mason Patriots': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2244.png',
    'Saint Louis': 'https://a.espncdn.com/i/teamlogos/ncaa/500/139.png',
    'Saint Louis Billikens': 'https://a.espncdn.com/i/teamlogos/ncaa/500/139.png',
    'Duquesne': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png',
    'Duquesne Dukes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2184.png',
    'Rhode Island': 'https://a.espncdn.com/i/teamlogos/ncaa/500/227.png',
    'Rhode Island Rams': 'https://a.espncdn.com/i/teamlogos/ncaa/500/227.png',
    'Richmond': 'https://a.espncdn.com/i/teamlogos/ncaa/500/257.png',
    'Richmond Spiders': 'https://a.espncdn.com/i/teamlogos/ncaa/500/257.png',
    'George Washington': 'https://a.espncdn.com/i/teamlogos/ncaa/500/45.png',
    'George Washington Colonials': 'https://a.espncdn.com/i/teamlogos/ncaa/500/45.png',
    'Fordham': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2230.png',
    'Fordham Rams': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2230.png',
    'La Salle': 'https://a.espncdn.com/i/teamlogos/ncaa/500/312.png',
    'La Salle Explorers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/312.png',
    'Massachusetts': 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png',
    'Massachusetts Minutemen': 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png',
    'UMass': 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png',

    // Other Notable CBB Programs
    'Gonzaga': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png',
    'Gonzaga Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png',
    'San Diego State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
    'San Diego State Aztecs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
    'Memphis': 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
    'Memphis Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
    'Wichita State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png',
    'Wichita State Shockers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2724.png',
    'Murray State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/93.png',
    'Murray State Racers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/93.png',
    'Belmont': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2057.png',
    'Belmont Bruins': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2057.png',
    'Drake': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png',
    'Drake Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2181.png',
    'Loyola Chicago': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2350.png',
    'Loyola Chicago Ramblers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2350.png',
    'Missouri State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png',
    'Missouri State Bears': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2623.png',
    'Northern Iowa': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2460.png',
    'Northern Iowa Panthers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2460.png',
    'Oral Roberts': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2490.png',
    'Oral Roberts Golden Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2490.png',
    'Colgate': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png',
    'Colgate Raiders': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2142.png',
    'UNLV': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png',
    'UNLV Rebels': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png',
    'New Mexico': 'https://a.espncdn.com/i/teamlogos/ncaa/500/167.png',
    'New Mexico Lobos': 'https://a.espncdn.com/i/teamlogos/ncaa/500/167.png',
    'Akron': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png',
    'Akron Zips': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png',
    'Buffalo': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
    'Buffalo Bulls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
    'Ohio': 'https://a.espncdn.com/i/teamlogos/ncaa/500/195.png',
    'Ohio Bobcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/195.png',
    'Miami (OH)': 'https://a.espncdn.com/i/teamlogos/ncaa/500/193.png',
    'Miami (OH) RedHawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/193.png',
    'Miami RedHawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/193.png',
    'UAB': 'https://a.espncdn.com/i/teamlogos/ncaa/500/5.png',
    'UAB Blazers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/5.png',
    'Temple': 'https://a.espncdn.com/i/teamlogos/ncaa/500/218.png',
    'Temple Owls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/218.png',
    'Tulsa': 'https://a.espncdn.com/i/teamlogos/ncaa/500/202.png',
    'Tulsa Golden Hurricane': 'https://a.espncdn.com/i/teamlogos/ncaa/500/202.png',
    'Tulane': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
    'Tulane Green Wave': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
    'SMU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
    'SMU Mustangs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
    'East Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
    'East Carolina Pirates': 'https://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
    'South Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
    'South Florida Bulls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
    'Iona': 'https://a.espncdn.com/i/teamlogos/ncaa/500/314.png',
    'Iona Gaels': 'https://a.espncdn.com/i/teamlogos/ncaa/500/314.png',
    'Hofstra': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2269.png',
    'Hofstra Pride': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2269.png',
    'Northeastern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/111.png',
    'Northeastern Huskies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/111.png',
    'Princeton': 'https://a.espncdn.com/i/teamlogos/ncaa/500/163.png',
    'Princeton Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/163.png',
    'Yale': 'https://a.espncdn.com/i/teamlogos/ncaa/500/43.png',
    'Yale Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/43.png',
    'Harvard': 'https://a.espncdn.com/i/teamlogos/ncaa/500/108.png',
    'Harvard Crimson': 'https://a.espncdn.com/i/teamlogos/ncaa/500/108.png',
    'Penn': 'https://a.espncdn.com/i/teamlogos/ncaa/500/219.png',
    'Penn Quakers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/219.png',
    'Cornell': 'https://a.espncdn.com/i/teamlogos/ncaa/500/172.png',
    'Cornell Big Red': 'https://a.espncdn.com/i/teamlogos/ncaa/500/172.png',

    // HBCUs and small conference teams
    'Alabama State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2011.png',
    'Alabama State Hornets': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2011.png',
    'Alabama A&M': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2010.png',
    'Alabama A&M Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2010.png',
    'Alcorn State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2016.png',
    'Alcorn State Braves': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2016.png',
    'Grambling': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png',
    'Grambling State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2755.png',
    'Southern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2582.png',
    'Southern Jaguars': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2582.png',
    'Jackson State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2296.png',
    'Jackson State Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2296.png',
    'Prairie View A&M': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2504.png',
    'Texas Southern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png',
    'Texas Southern Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2640.png',
    'Howard': 'https://a.espncdn.com/i/teamlogos/ncaa/500/47.png',
    'Howard Bison': 'https://a.espncdn.com/i/teamlogos/ncaa/500/47.png',
    'Morgan State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png',
    'Morgan State Bears': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2415.png',
    'Norfolk State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2452.png',
    'Norfolk State Spartans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2452.png',
    'North Carolina A&T': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2448.png',
    'North Carolina Central': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png',
    'Bethune-Cookman': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2065.png',
    'Florida A&M': 'https://a.espncdn.com/i/teamlogos/ncaa/500/50.png',
    'Coppin State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2154.png',
    'Delaware State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2169.png',
    'South Carolina State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2569.png',
    'Mississippi Valley State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2400.png',
    'Tennessee State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2634.png',
    'Tennessee Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2635.png',
    'Wofford': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2747.png',
    'Chattanooga': 'https://a.espncdn.com/i/teamlogos/ncaa/500/236.png',
    'East Tennessee State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2197.png',
    'ETSU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2197.png',
    'Furman': 'https://a.espncdn.com/i/teamlogos/ncaa/500/231.png',
    'Samford': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2535.png',
    'Western Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2717.png',
    'Mercer': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2382.png',
    'Montana': 'https://a.espncdn.com/i/teamlogos/ncaa/500/149.png',
    'Montana State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/147.png',
    'North Dakota State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png',
    'South Dakota State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2571.png',
    'South Dakota': 'https://a.espncdn.com/i/teamlogos/ncaa/500/233.png',
    'North Dakota': 'https://a.espncdn.com/i/teamlogos/ncaa/500/155.png',
    'Weber State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2692.png',
    'Idaho State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/304.png',
    'Idaho': 'https://a.espncdn.com/i/teamlogos/ncaa/500/70.png',
    'Eastern Washington': 'https://a.espncdn.com/i/teamlogos/ncaa/500/331.png',
    'Northern Arizona': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2464.png',
    'Sacramento State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/16.png',
    'Portland State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2501.png',
    'Cal Poly': 'https://a.espncdn.com/i/teamlogos/ncaa/500/13.png',
    'Vermont': 'https://a.espncdn.com/i/teamlogos/ncaa/500/261.png',
    'Stony Brook': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2619.png',
    'Albany': 'https://a.espncdn.com/i/teamlogos/ncaa/500/399.png',
    'Maine': 'https://a.espncdn.com/i/teamlogos/ncaa/500/311.png',
    'Drexel': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2182.png',
    'Towson': 'https://a.espncdn.com/i/teamlogos/ncaa/500/119.png',
    'Campbell': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2097.png',
    'Elon': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2210.png',
    'Winthrop': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2741.png',
    'Austin Peay': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png',
    'Eastern Kentucky': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2198.png',
    'Morehead State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2413.png',
    'Illinois State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2287.png',
    'Indiana State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/282.png',
    'Southern Illinois': 'https://a.espncdn.com/i/teamlogos/ncaa/500/79.png',
    'Valparaiso': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2674.png',
    'Louisiana Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png',
    'Nicholls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2447.png',
    'McNeese': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2377.png',
    'Sam Houston': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png',
    'Abilene Christian': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2000.png',
    'Lamar': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2320.png',
    'Southeast Missouri State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2546.png',
    'Kennesaw State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/338.png',
    'Oakland': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2473.png',
    'Wright State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2750.png',
    'Cleveland State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/325.png',
    'Milwaukee': 'https://a.espncdn.com/i/teamlogos/ncaa/500/270.png',
    'Green Bay': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png',
    'Detroit Mercy': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2174.png',
    'Youngstown State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2894.png',
    // Big Sky (missing)
    'Northern Colorado': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png',
    'Northern Colorado Bears': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2458.png',
    'Southern Utah': 'https://a.espncdn.com/i/teamlogos/ncaa/500/253.png',
    'Southern Utah Thunderbirds': 'https://a.espncdn.com/i/teamlogos/ncaa/500/253.png',

    // Southern Conference (missing)
    'The Citadel': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png',
    'VMI': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png',
    'VMI Keydets': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2739.png',
    'UNC Greensboro': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png',
    'UNC Greensboro Spartans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2430.png',

    // ASUN
    'Bellarmine': 'https://a.espncdn.com/i/teamlogos/ncaa/500/91.png',
    'Bellarmine Knights': 'https://a.espncdn.com/i/teamlogos/ncaa/500/91.png',
    'Central Arkansas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2110.png',
    'Central Arkansas Bears': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2110.png',
    'FGCU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/526.png',
    'Florida Gulf Coast': 'https://a.espncdn.com/i/teamlogos/ncaa/500/526.png',
    'Florida Gulf Coast Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/526.png',
    'Jacksonville': 'https://a.espncdn.com/i/teamlogos/ncaa/500/294.png',
    'Jacksonville Dolphins': 'https://a.espncdn.com/i/teamlogos/ncaa/500/294.png',
    'Lipscomb': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png',
    'Lipscomb Bisons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2344.png',
    'North Alabama': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2453.png',
    'North Alabama Lions': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2453.png',
    'North Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2454.png',
    'North Florida Ospreys': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2454.png',
    'Queens': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2954.png',
    'Queens Royals': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2954.png',
    'Stetson': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png',
    'Stetson Hatters': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2608.png',

    // Big South
    'Charleston Southern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2111.png',
    'Charleston Southern Buccaneers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2111.png',
    'Gardner-Webb': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png',
    'Gardner-Webb Runnin Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2241.png',
    'High Point': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2272.png',
    'High Point Panthers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2272.png',
    'Longwood': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2347.png',
    'Longwood Lancers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2347.png',
    'Presbyterian': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png',
    'Presbyterian Blue Hose': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2502.png',
    'Radford': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2513.png',
    'Radford Highlanders': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2513.png',
    'UNC Asheville': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png',
    'UNC Asheville Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2428.png',

    // Northeast Conference
    'Bryant': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2801.png',
    'Bryant Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2801.png',
    'Central Connecticut': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2115.png',
    'Central Connecticut Blue Devils': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2115.png',
    'LIU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2650.png',
    'LIU Sharks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2650.png',
    'Merrimack': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2893.png',
    'Merrimack Warriors': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2893.png',
    "Mount St. Mary's": 'https://a.espncdn.com/i/teamlogos/ncaa/500/2416.png',
    'Sacred Heart': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2529.png',
    'Sacred Heart Pioneers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2529.png',
    'Saint Francis': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2545.png',
    'Saint Francis Red Flash': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2545.png',
    'Wagner': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2678.png',
    'Wagner Seahawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2678.png',
    'Stonehill': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2967.png',
    'Stonehill Skyhawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2967.png',

    // Ohio Valley / Southland (missing)
    'Lindenwood': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2934.png',
    'Lindenwood Lions': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2934.png',
    'Little Rock': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png',
    'Little Rock Trojans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2029.png',
    'SIU Edwardsville': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2565.png',
    'SIUE': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2565.png',
    'UT Martin': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2651.png',
    'UT Martin Skyhawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2651.png',
    'Houston Baptist': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2277.png',
    'HBU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2277.png',
    'Incarnate Word': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2854.png',
    'Incarnate Word Cardinals': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2854.png',
    'Northwestern State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png',
    'Northwestern State Demons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2466.png',
    'Texas A&M-Corpus Christi': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png',
    'SE Louisiana': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2548.png',
    'Southeastern Louisiana': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2548.png',

    // MEAC (missing)
    'Hampton': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2261.png',
    'Hampton Pirates': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2261.png',
    'Maryland Eastern Shore': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2379.png',
    'UMES': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2379.png',

    // Sun Belt Conference
    'Georgia Southern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/290.png',
    'Georgia Southern Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/290.png',
    'Troy': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
    'Troy Trojans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
    'South Alabama': 'https://a.espncdn.com/i/teamlogos/ncaa/500/6.png',
    'South Alabama Jaguars': 'https://a.espncdn.com/i/teamlogos/ncaa/500/6.png',
    'Louisiana': 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    'Louisiana Ragin Cajuns': 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    'Louisiana Lafayette': 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    'UL Lafayette': 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    'Louisiana Monroe': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png',
    'ULM': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png',
    'Appalachian State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
    'App State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
    'Coastal Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/324.png',
    'Coastal Carolina Chanticleers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/324.png',
    'James Madison': 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png',
    'James Madison Dukes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png',
    'Arkansas State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png',
    'Arkansas State Red Wolves': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png',
    'Texas State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/326.png',
    'Texas State Bobcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/326.png',
    'Old Dominion': 'https://a.espncdn.com/i/teamlogos/ncaa/500/295.png',
    'Old Dominion Monarchs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/295.png',
    'Southern Miss': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png',
    'Southern Mississippi': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png',
    'Marshall': 'https://a.espncdn.com/i/teamlogos/ncaa/500/276.png',
    'Marshall Thundering Herd': 'https://a.espncdn.com/i/teamlogos/ncaa/500/276.png',
    'UTSA': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
    'UTSA Roadrunners': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
    'Georgia State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
    'Georgia State Panthers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
    // Mountain West
    'Air Force': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
    'Air Force Falcons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
    'Boise State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png',
    'Boise State Broncos': 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png',
    'Colorado State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/36.png',
    'Colorado State Rams': 'https://a.espncdn.com/i/teamlogos/ncaa/500/36.png',
    'Fresno State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/278.png',
    'Fresno State Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/278.png',
    'Nevada': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
    'Nevada Wolf Pack': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
    'Utah State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/328.png',
    'Utah State Aggies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/328.png',
    'Wyoming': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png',
    'Wyoming Cowboys': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png',
    'San Jose State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/23.png',
    'San Jose State Spartans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/23.png',

    // American Athletic Conference
    'Charlotte': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png',
    'Charlotte 49ers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png',
    'Florida Atlantic': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png',
    'Florida Atlantic Owls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png',
    'North Texas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
    'North Texas Mean Green': 'https://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
    'Rice': 'https://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
    'Rice Owls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
    'Navy': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',
    'Navy Midshipmen': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',

    // Conference USA
    'Western Kentucky': 'https://a.espncdn.com/i/teamlogos/ncaa/500/98.png',
    'Western Kentucky Hilltoppers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/98.png',
    'Middle Tennessee': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
    'Middle Tennessee Blue Raiders': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
    'Liberty': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png',
    'Liberty Flames': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png',
    'New Mexico State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/166.png',
    'New Mexico State Aggies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/166.png',
    'Florida International': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png',
    'FIU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png',
    'Jacksonville State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2300.png',
    'Jacksonville State Gamecocks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2300.png',
    'UTEP': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png',
    'UTEP Miners': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png',

    // WCC
    "Saint Mary's": 'https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png',
    "Saint Mary's Gaels": 'https://a.espncdn.com/i/teamlogos/ncaa/500/2550.png',
    'Portland': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2506.png',
    'Portland Pilots': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2506.png',
    'Pepperdine': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2492.png',
    'Pepperdine Waves': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2492.png',
    'Loyola Marymount': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2351.png',
    'Loyola Marymount Lions': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2351.png',
    'LMU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2351.png',
    'San Francisco': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png',
    'San Francisco Dons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2539.png',
    'Pacific': 'https://a.espncdn.com/i/teamlogos/ncaa/500/279.png',
    'Pacific Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/279.png',

    // Big West
    'UC Irvine': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2260.png',
    'UC Irvine Anteaters': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2260.png',
    'UC Davis': 'https://a.espncdn.com/i/teamlogos/ncaa/500/302.png',
    'UC Davis Aggies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/302.png',
    'UC Riverside': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2576.png',
    'UC Riverside Highlanders': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2576.png',
    'UC Santa Barbara': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2565.png',
    'UCSB': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2565.png',
    'Cal State Northridge': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2290.png',
    'CSUN': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2290.png',
    'Cal State Fullerton': 'https://a.espncdn.com/i/teamlogos/ncaa/500/42.png',
    'Cal State Fullerton Titans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/42.png',
    'Hawaii': 'https://a.espncdn.com/i/teamlogos/ncaa/500/62.png',
    'Hawaii Warriors': 'https://a.espncdn.com/i/teamlogos/ncaa/500/62.png',
    'Long Beach State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
    'UC San Diego': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2610.png',
    'UC San Diego Tritons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2610.png',

    // MAAC
    'Rider': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2503.png',
    'Rider Broncs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2503.png',
    'Siena': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2561.png',
    'Siena Saints': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2561.png',
    'Manhattan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2372.png',
    'Manhattan Jaspers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2372.png',
    "Saint Peter's": 'https://a.espncdn.com/i/teamlogos/ncaa/500/2530.png',
    'Monmouth': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2409.png',
    'Monmouth Hawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2409.png',
    'Quinnipiac': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2508.png',
    'Quinnipiac Bobcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2508.png',
    'Marist': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2368.png',
    'Marist Red Foxes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2368.png',
    'Niagara': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2442.png',
    'Niagara Purple Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2442.png',
    'Canisius': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png',
    'Canisius Golden Griffins': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2099.png',
    'Fairfield': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2221.png',
    'Fairfield Stags': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2221.png',

  };

  // Try exact match first
  if (teamLogos[teamName]) {
    return teamLogos[teamName];
  }

  // Try case-insensitive exact match
  const lowerTeam = teamName.toLowerCase();
  const foundExact = Object.keys(teamLogos).find(k => k.toLowerCase() === lowerTeam);
  if (foundExact) return teamLogos[foundExact];

  // Partial match - only allow prefix matches to avoid "Alabama" matching "Alabama State"
  const foundPartial = Object.keys(teamLogos).find(key => {
    const lowerKey = key.toLowerCase();
    if (lowerTeam === lowerKey) return true;
    if (lowerTeam.startsWith(lowerKey + ' ')) return true;
    if (lowerKey.startsWith(lowerTeam + ' ')) return true;
    return false;
  });
  if (foundPartial) return teamLogos[foundPartial];

  // Fallback: try ESPN CDN with numeric ID lookup
  return generateESPNLogoURL(teamName);
};

const generateESPNLogoURL = (teamName) => {
  const cleanName = teamName.replace(/\s+(Aggies|Bears|Bearcats|Beavers|Billikens|Blazers|Blue Devils|Blue Demons|Bluejays|Bobcats|Boilermakers|Broncos|Bruins|Buckeyes|Buffaloes|Bulldogs|Bulls|Cardinals|Cavaliers|Chanticleers|Chippewas|Colonials|Commodores|Cornhuskers|Cougars|Cowboys|Crimson|Crimson Tide|Cyclones|Demon Deacons|Dukes|Eagles|Explorers|Falcons|Fighting Irish|Flames|Flyers|Friars|Gators|Gaels|Golden Bears|Golden Eagles|Golden Flashes|Golden Gophers|Golden Hurricane|Green Wave|Hokies|Hoosiers|Horned Frogs|Hoyas|Huskies|Hurricanes|Illini|Jayhawks|Knights|Lobos|Longhorns|Musketeers|Nittany Lions|Orange|Owls|Panthers|Patriots|Pirates|Racers|Ramblers|Rams|Razorbacks|Red Raiders|Red Storm|RedHawks|Rockets|Scarlet Knights|Seminoles|Shockers|Sooners|Spartans|Sun Devils|Tar Heels|Terrapins|Tigers|Trojans|Utes|Volunteers|Wildcats|Wolf Pack|Wolverines|Yellow Jackets|Zips)$/i, '').trim();

  const espnIds = {
    'Alabama': '333', 'Arizona': '12', 'Arizona State': '9', 'Arkansas': '8',
    'Auburn': '2', 'Baylor': '239', 'Boston College': '103', 'BYU': '252',
    'Butler': '2086', 'California': '25', 'Cincinnati': '2132', 'Clemson': '228',
    'Colgate': '2142', 'Colorado': '38', 'Connecticut': '41', 'Creighton': '156',
    'Davidson': '2166', 'Dayton': '2168', 'DePaul': '305', 'Drake': '2181',
    'Duke': '150', 'Duquesne': '2184', 'Florida': '57', 'Florida State': '52',
    'Fordham': '2230', 'George Mason': '2244', 'George Washington': '45',
    'Georgetown': '46', 'Georgia': '61', 'Georgia Tech': '59', 'Gonzaga': '2250',
    'Harvard': '108', 'Houston': '248', 'Illinois': '356', 'Indiana': '84',
    'Iona': '314', 'Iowa': '2294', 'Iowa State': '66', 'Kansas': '2305',
    'Kansas State': '2306', 'Kentucky': '96', 'La Salle': '312', 'Louisiana': '309',
    'Loyola Chicago': '2350', 'LSU': '99', 'Marquette': '269', 'Maryland': '120',
    'Massachusetts': '113', 'Memphis': '235', 'Miami': '2390', 'Miami (OH)': '193',
    'Michigan': '130', 'Michigan State': '127', 'Minnesota': '135', 'Missouri': '142',
    'Missouri State': '2623', 'Murray State': '93', 'NC State': '152',
    'Nebraska': '158', 'New Mexico': '167', 'North Carolina': '153',
    'Northern Iowa': '2460', 'Northwestern': '77', 'Notre Dame': '87',
    'Ohio': '195', 'Ohio State': '194', 'Oklahoma': '201', 'Oklahoma State': '197',
    'Ole Miss': '145', 'Oral Roberts': '2490', 'Oregon': '2483', 'Penn': '219',
    'Penn State': '213', 'Pittsburgh': '221', 'Princeton': '163', 'Providence': '2507',
    'Purdue': '2509', 'Rhode Island': '227', 'Richmond': '257', 'Rutgers': '164',
    'San Diego State': '21', 'Seton Hall': '2550', 'SMU': '2567', 'South Carolina': '2579',
    'Stanford': '24', 'St. John\'s': '2599', 'Syracuse': '183', 'TCU': '2628',
    'Temple': '218', 'Tennessee': '2633', 'Texas': '251', 'Texas A&M': '245',
    'Texas Tech': '2641', 'Tulane': '2655', 'Tulsa': '202', 'UAB': '5',
    'UCF': '2116', 'UCLA': '26', 'UConn': '41', 'UNLV': '2439', 'USC': '30',
    'Utah': '254', 'Vanderbilt': '238', 'VCU': '2670', 'Villanova': '222',
    'Virginia': '258', 'Virginia Tech': '259', 'Wake Forest': '154',
    'Washington': '264', 'West Virginia': '277', 'Wichita State': '2724',
    'Wisconsin': '275', 'Xavier': '2755', 'Yale': '43',
  };

  const teamId = espnIds[cleanName] || espnIds[teamName];
  if (teamId) {
    return `https://a.espncdn.com/i/teamlogos/ncaa/500/${teamId}.png`;
  }

  return '';
};

export const getCBBTeamShortName = (teamName) => {
  const shortNames = {
    // ACC
    'Duke': 'DUKE', 'Duke Blue Devils': 'DUKE',
    'North Carolina': 'UNC', 'North Carolina Tar Heels': 'UNC', 'UNC': 'UNC',
    'Virginia': 'UVA', 'Virginia Cavaliers': 'UVA',
    'Virginia Tech': 'VT', 'Virginia Tech Hokies': 'VT',
    'Syracuse': 'SYR', 'Syracuse Orange': 'SYR',
    'Louisville': 'LOU', 'Louisville Cardinals': 'LOU',
    'Florida State': 'FSU', 'Florida State Seminoles': 'FSU',
    'Clemson': 'CLEM', 'Clemson Tigers': 'CLEM',
    'Wake Forest': 'WF', 'Wake Forest Demon Deacons': 'WF',
    'Pittsburgh': 'PITT', 'Pittsburgh Panthers': 'PITT',
    'Georgia Tech': 'GT', 'Georgia Tech Yellow Jackets': 'GT',
    'Boston College': 'BC', 'Boston College Eagles': 'BC',
    'NC State': 'NCST', 'NC State Wolfpack': 'NCST',
    'Notre Dame': 'ND', 'Notre Dame Fighting Irish': 'ND',
    'Miami': 'MIA', 'Miami Hurricanes': 'MIA',
    'Stanford': 'STAN', 'Stanford Cardinal': 'STAN',

    // Big Ten
    'Michigan State': 'MSU', 'Michigan State Spartans': 'MSU',
    'Michigan': 'MICH', 'Michigan Wolverines': 'MICH',
    'Ohio State': 'OSU', 'Ohio State Buckeyes': 'OSU',
    'Purdue': 'PUR', 'Purdue Boilermakers': 'PUR',
    'Illinois': 'ILL', 'Illinois Fighting Illini': 'ILL',
    'Indiana': 'IND', 'Indiana Hoosiers': 'IND',
    'Wisconsin': 'WIS', 'Wisconsin Badgers': 'WIS',
    'Iowa': 'IOWA', 'Iowa Hawkeyes': 'IOWA',
    'Maryland': 'UMD', 'Maryland Terrapins': 'UMD',
    'Penn State': 'PSU', 'Penn State Nittany Lions': 'PSU',
    'Minnesota': 'MINN', 'Minnesota Golden Gophers': 'MINN',
    'Northwestern': 'NW', 'Northwestern Wildcats': 'NW',
    'Nebraska': 'NEB', 'Nebraska Cornhuskers': 'NEB',
    'Rutgers': 'RUT', 'Rutgers Scarlet Knights': 'RUT',
    'UCLA': 'UCLA', 'UCLA Bruins': 'UCLA',
    'USC': 'USC', 'USC Trojans': 'USC',
    'Oregon': 'ORE', 'Oregon Ducks': 'ORE',
    'Washington': 'WASH', 'Washington Huskies': 'WASH',

    // Big 12
    'Kansas': 'KU', 'Kansas Jayhawks': 'KU',
    'Kansas State': 'KSU', 'Kansas State Wildcats': 'KSU',
    'Baylor': 'BAY', 'Baylor Bears': 'BAY',
    'Texas': 'TEX', 'Texas Longhorns': 'TEX',
    'Texas Tech': 'TTU', 'Texas Tech Red Raiders': 'TTU',
    'Iowa State': 'ISU', 'Iowa State Cyclones': 'ISU',
    'Oklahoma State': 'OKST', 'Oklahoma State Cowboys': 'OKST',
    'West Virginia': 'WVU', 'West Virginia Mountaineers': 'WVU',
    'TCU': 'TCU', 'TCU Horned Frogs': 'TCU',
    'Houston': 'HOU', 'Houston Cougars': 'HOU',
    'Cincinnati': 'CIN', 'Cincinnati Bearcats': 'CIN',
    'UCF': 'UCF', 'UCF Knights': 'UCF',
    'BYU': 'BYU', 'BYU Cougars': 'BYU',
    'Colorado': 'COLO', 'Colorado Buffaloes': 'COLO',
    'Utah': 'UTAH', 'Utah Utes': 'UTAH',
    'Arizona': 'ARIZ', 'Arizona Wildcats': 'ARIZ',
    'Arizona State': 'ASU', 'Arizona State Sun Devils': 'ASU',
    'Oklahoma': 'OU', 'Oklahoma Sooners': 'OU',

    // SEC
    'Kentucky': 'UK', 'Kentucky Wildcats': 'UK',
    'Tennessee': 'TENN', 'Tennessee Volunteers': 'TENN',
    'Alabama': 'ALA', 'Alabama Crimson Tide': 'ALA',
    'Auburn': 'AUB', 'Auburn Tigers': 'AUB',
    'Arkansas': 'ARK', 'Arkansas Razorbacks': 'ARK',
    'Florida': 'FLA', 'Florida Gators': 'FLA',
    'Georgia': 'UGA', 'Georgia Bulldogs': 'UGA',
    'LSU': 'LSU', 'LSU Tigers': 'LSU',
    'Missouri': 'MIZ', 'Missouri Tigers': 'MIZ',
    'Ole Miss': 'MISS', 'Ole Miss Rebels': 'MISS',
    'Mississippi State': 'MSST', 'Mississippi State Bulldogs': 'MSST',
    'South Carolina': 'SC', 'South Carolina Gamecocks': 'SC',
    'Texas A&M': 'TAMU', 'Texas A&M Aggies': 'TAMU',
    'Vanderbilt': 'VAN', 'Vanderbilt Commodores': 'VAN',

    // Big East
    'UConn': 'CONN', 'UConn Huskies': 'CONN', 'Connecticut': 'CONN',
    'Villanova': 'NOVA', 'Villanova Wildcats': 'NOVA',
    'Marquette': 'MARQ', 'Marquette Golden Eagles': 'MARQ',
    'Creighton': 'CREI', 'Creighton Bluejays': 'CREI',
    'Xavier': 'XAV', 'Xavier Musketeers': 'XAV',
    'Seton Hall': 'SHU', 'Seton Hall Pirates': 'SHU',
    'Providence': 'PROV', 'Providence Friars': 'PROV',
    'Georgetown': 'GTOWN', 'Georgetown Hoyas': 'GTOWN',
    'Butler': 'BUT', 'Butler Bulldogs': 'BUT',
    "St. John's": 'STJ', "St. John's Red Storm": 'STJ',
    'DePaul': 'DEP', 'DePaul Blue Demons': 'DEP',

    // Others
    'Gonzaga': 'GONZ', 'Gonzaga Bulldogs': 'GONZ',
    'Memphis': 'MEM', 'Memphis Tigers': 'MEM',
    'San Diego State': 'SDSU', 'San Diego State Aztecs': 'SDSU',
    'Dayton': 'DAY', 'Dayton Flyers': 'DAY',
    'VCU': 'VCU', 'VCU Rams': 'VCU',
    'Wichita State': 'WSU', 'Wichita State Shockers': 'WSU',
    'George Mason': 'GMU', 'George Mason Patriots': 'GMU',
    'Saint Louis': 'SLU', 'Saint Louis Billikens': 'SLU',
    'UNLV': 'UNLV', 'UNLV Rebels': 'UNLV',
    'Ohio': 'OHIO', 'Ohio Bobcats': 'OHIO',
    'Miami (OH)': 'MIOH', 'Miami (OH) RedHawks': 'MIOH',
    'UAB': 'UAB', 'UAB Blazers': 'UAB',
    'Temple': 'TEMP', 'Temple Owls': 'TEMP',
    'Murray State': 'MUR', 'Murray State Racers': 'MUR',
    'Loyola Chicago': 'LOY', 'Loyola Chicago Ramblers': 'LOY',
    // Sun Belt
    'Georgia Southern': 'GSU', 'Georgia Southern Eagles': 'GSU',
    'Troy': 'TROY', 'Troy Trojans': 'TROY',
    'South Alabama': 'USA', 'South Alabama Jaguars': 'USA',
    'Louisiana': 'ULL', 'Louisiana Ragin Cajuns': 'ULL', 'Louisiana Lafayette': 'ULL', 'UL Lafayette': 'ULL',
    'Louisiana Monroe': 'ULM', 'ULM': 'ULM',
    'Appalachian State': 'APP', 'App State': 'APP',
    'Coastal Carolina': 'CCU', 'Coastal Carolina Chanticleers': 'CCU',
    'James Madison': 'JMU', 'James Madison Dukes': 'JMU',
    'Arkansas State': 'ARST', 'Arkansas State Red Wolves': 'ARST',
    'Texas State': 'TXST', 'Texas State Bobcats': 'TXST',
    'Old Dominion': 'ODU', 'Old Dominion Monarchs': 'ODU',
    'Southern Miss': 'USM', 'Southern Mississippi': 'USM',
    'Marshall': 'MRSH', 'Marshall Thundering Herd': 'MRSH',
    'UTSA': 'UTSA', 'UTSA Roadrunners': 'UTSA',
    // Mountain West
    'Air Force': 'AFA', 'Boise State': 'BSU', 'Boise State Broncos': 'BSU',
    'Colorado State': 'CSU', 'Colorado State Rams': 'CSU',
    'Fresno State': 'FRES', 'Nevada': 'NEV', 'Utah State': 'USU',
    'Wyoming': 'WYO', 'San Jose State': 'SJSU',
    // AAC
    'North Texas': 'UNT', 'Rice': 'RICE', 'Navy': 'NAVY',
    // CUSA
    'Western Kentucky': 'WKU', 'Middle Tennessee': 'MTSU', 'Liberty': 'LIB',
    'New Mexico State': 'NMST', 'Florida International': 'FIU',
    'Jacksonville State': 'JVST', 'UTEP': 'UTEP',
    // WCC
    "Saint Mary's": 'SMC', "Saint Mary's Gaels": 'SMC',
    'Portland': 'PORT', 'Pepperdine': 'PEPP', 'Loyola Marymount': 'LMU',
    'San Francisco': 'USF', 'Pacific': 'PAC',
    // Big West
    'UC Irvine': 'UCI', 'UC Davis': 'UCD', 'UC Riverside': 'UCR',
    'UC Santa Barbara': 'UCSB', 'UCSB': 'UCSB',
    'Cal State Northridge': 'CSUN', 'CSUN': 'CSUN',
    'Cal State Fullerton': 'CSUF', 'Hawaii': 'HAW',
    'Long Beach State': 'LBST', 'UC San Diego': 'UCSD',
    // MAAC
    'Rider': 'RID', 'Siena': 'SIE', 'Manhattan': 'MAN',
    "Saint Peter's": 'SPU', 'Monmouth': 'MON', 'Quinnipiac': 'QUIN',
    'Marist': 'MAR', 'Niagara': 'NIA', 'Canisius': 'CAN', 'Fairfield': 'FAIR',
    // Big Sky missing
    'Northern Colorado': 'UNCO', 'Southern Utah': 'SUU',
    // Southern Conference missing
    'The Citadel': 'CIT', 'VMI': 'VMI', 'UNC Greensboro': 'UNCG',
    // ASUN
    'Bellarmine': 'BEL', 'Central Arkansas': 'UCA', 'FGCU': 'FGCU',
    'Florida Gulf Coast': 'FGCU', 'Jacksonville': 'JAX', 'Lipscomb': 'LIP',
    'North Alabama': 'UNA', 'North Florida': 'UNF', 'Queens': 'QUNS', 'Stetson': 'STET',
    // Big South
    'Charleston Southern': 'CSU', 'Gardner-Webb': 'GWU', 'High Point': 'HPU',
    'Longwood': 'LONG', 'Presbyterian': 'PC', 'Radford': 'RAD', 'UNC Asheville': 'UNCA',
    // NEC
    'Bryant': 'BRY', 'Central Connecticut': 'CCSU', 'LIU': 'LIU',
    'Merrimack': 'MER', 'Sacred Heart': 'SHU',
    'Saint Francis': 'SFU', 'Wagner': 'WAG', 'Stonehill': 'STON',
    // OVC/Southland missing
    'Lindenwood': 'LIN', 'Little Rock': 'UALR', 'SIU Edwardsville': 'SIUE',
    'UT Martin': 'UTM', 'Houston Baptist': 'HBU', 'Incarnate Word': 'UIW',
    'Northwestern State': 'NWST', 'Texas A&M-Corpus Christi': 'TAMC',
    'SE Louisiana': 'SELA', 'Southeastern Louisiana': 'SELA',
    // MEAC missing
    'Hampton': 'HAM', 'Maryland Eastern Shore': 'UMES',


    'Georgia State': 'GSU', 'Georgia State Panthers': 'GSU',
  };

  if (shortNames[teamName]) return shortNames[teamName];

  const foundKey = Object.keys(shortNames).find(key =>
    teamName.toLowerCase().includes(key.toLowerCase()) ||
    key.toLowerCase().includes(teamName.toLowerCase())
  );

  return foundKey ? shortNames[foundKey] : teamName.substring(0, 4).toUpperCase();
};
