/**
 * College Football Team Logos
 * Using ESPN CDN for team logos
 */

export const getCFBTeamLogo = (teamName) => {
  const teamLogos = {
    // Top 25 Teams
    'Oregon': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',
    'Oregon Ducks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png',
    'Georgia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
    'Georgia Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png',
    'Ohio State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
    'Ohio State Buckeyes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png',
    'Penn State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
    'Penn State Nittany Lions': 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png',
    'Texas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
    'Texas Longhorns': 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png',
    'Miami': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
    'Miami Hurricanes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png',
    'Alabama': 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
    'Alabama Crimson Tide': 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
    'Ole Miss': 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
    'Ole Miss Rebels': 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
    'Mississippi': 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png',
    'Tennessee': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
    'Tennessee Volunteers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
    'LSU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
    'LSU Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png',
    'Clemson': 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
    'Clemson Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png',
    'Iowa State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
    'Iowa State Cyclones': 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
    'BYU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
    'BYU Cougars': 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png',
    'Notre Dame': 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
    'Notre Dame Fighting Irish': 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png',
    'Texas A&M': 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
    'Texas A&M Aggies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png',
    'Kansas State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
    'Kansas State Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png',
    'Oklahoma': 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
    'Oklahoma Sooners': 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png',
    'USC': 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
    'USC Trojans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
    'Southern California': 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png',
    'Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
    'Michigan Wolverines': 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
    'SMU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
    'SMU Mustangs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png',
    'Louisville': 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
    'Louisville Cardinals': 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png',
    'Missouri': 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
    'Missouri Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png',
    'Illinois': 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
    'Illinois Fighting Illini': 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png',
    'Boise State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png',
    'Boise State Broncos': 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png',
    'Washington': 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png',
    'Washington Huskies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png',

    // Additional common teams
    'Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
    'Florida Gators': 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
    'Auburn': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
    'Auburn Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png',
    'Wisconsin': 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
    'Wisconsin Badgers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
    'Oklahoma State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
    'Oklahoma State Cowboys': 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png',
    'Utah': 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
    'Utah Utes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png',
    'Oregon State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png',
    'Oregon State Beavers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png',
    'Florida State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
    'Florida State Seminoles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png',
    'North Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
    'North Carolina Tar Heels': 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
    'UCLA': 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
    'UCLA Bruins': 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png',
    'Arizona': 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
    'Arizona Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
    'Arizona State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
    'Arizona State Sun Devils': 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png',
    'Colorado': 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
    'Colorado Buffaloes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png',
    'Nebraska': 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
    'Nebraska Cornhuskers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png',
    'Kentucky': 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
    'Kentucky Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png',
    'South Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png',
    'South Carolina Gamecocks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png',
    'Vanderbilt': 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
    'Vanderbilt Commodores': 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png',
    'Arkansas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
    'Arkansas Razorbacks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
    'Mississippi State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
    'Mississippi State Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png',
    'TCU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
    'TCU Horned Frogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png',
    'Baylor': 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
    'Baylor Bears': 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png',
    'West Virginia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
    'West Virginia Mountaineers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png',
    'Texas Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
    'Texas Tech Red Raiders': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
    'Iowa': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
    'Iowa Hawkeyes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png',
    'Minnesota': 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
    'Minnesota Golden Gophers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png',
    'Northwestern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
    'Northwestern Wildcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png',
    'Purdue': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
    'Purdue Boilermakers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
    'Indiana': 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
    'Indiana Hoosiers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png',
    'Maryland': 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
    'Maryland Terrapins': 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png',
    'Rutgers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
    'Rutgers Scarlet Knights': 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png',
    'Michigan State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
    'Michigan State Spartans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png',
    'Stanford': 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
    'Stanford Cardinal': 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png',
    'California': 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png',
    'California Golden Bears': 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png',
    'Duke': 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
    'Duke Blue Devils': 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
    'Virginia': 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
    'Virginia Cavaliers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png',
    'Virginia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
    'Virginia Tech Hokies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png',
    'Pittsburgh': 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
    'Pittsburgh Panthers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png',
    'NC State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
    'NC State Wolfpack': 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png',
    'Syracuse': 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
    'Syracuse Orange': 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png',
    'Boston College': 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
    'Boston College Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png',
    'Wake Forest': 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
    'Wake Forest Demon Deacons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png',
    'Georgia Tech': 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
    'Georgia Tech Yellow Jackets': 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png',
    'Memphis': 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
    'Memphis Tigers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png',
    'South Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
    'South Florida Bulls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',
    'USF': 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png',

    // Additional schools
    'Houston': 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
    'Houston Cougars': 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
    'Akron': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png',
    'Akron Zips': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png',
    'UAB': 'https://a.espncdn.com/i/teamlogos/ncaa/500/5.png',
    'UAB Blazers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/5.png',
    'Cincinnati': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
    'Cincinnati Bearcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png',
    'UCF': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
    'UCF Knights': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
    'Central Florida': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png',
    'Tulane': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
    'Tulane Green Wave': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png',
    'East Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
    'East Carolina Pirates': 'https://a.espncdn.com/i/teamlogos/ncaa/500/151.png',
    'Temple': 'https://a.espncdn.com/i/teamlogos/ncaa/500/218.png',
    'Temple Owls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/218.png',
    'Tulsa': 'https://a.espncdn.com/i/teamlogos/ncaa/500/202.png',
    'Tulsa Golden Hurricane': 'https://a.espncdn.com/i/teamlogos/ncaa/500/202.png',
    'Navy': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',
    'Navy Midshipmen': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png',
    'Army': 'https://a.espncdn.com/i/teamlogos/ncaa/500/349.png',
    'Army Black Knights': 'https://a.espncdn.com/i/teamlogos/ncaa/500/349.png',
    'Air Force': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
    'Air Force Falcons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png',
    'San Diego State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
    'San Diego State Aztecs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png',
    'UNLV': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png',
    'UNLV Rebels': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png',
    'Fresno State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/278.png',
    'Fresno State Bulldogs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/278.png',
    'Nevada': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
    'Nevada Wolf Pack': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png',
    'New Mexico': 'https://a.espncdn.com/i/teamlogos/ncaa/500/167.png',
    'New Mexico Lobos': 'https://a.espncdn.com/i/teamlogos/ncaa/500/167.png',
    'Wyoming': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2840.png',
    'Wyoming Cowboys': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2840.png',
    'Hawaii': 'https://a.espncdn.com/i/teamlogos/ncaa/500/62.png',
    'Hawaii Rainbow Warriors': 'https://a.espncdn.com/i/teamlogos/ncaa/500/62.png',
    'San Jose State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/23.png',
    'San Jose State Spartans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/23.png',
    'Colorado State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/36.png',
    'Colorado State Rams': 'https://a.espncdn.com/i/teamlogos/ncaa/500/36.png',
    'Utah State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/328.png',
    'Utah State Aggies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/328.png',
    'Buffalo': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
    'Buffalo Bulls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png',
    'Miami (OH)': 'https://a.espncdn.com/i/teamlogos/ncaa/500/193.png',
    'Miami RedHawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/193.png',
    'Ohio': 'https://a.espncdn.com/i/teamlogos/ncaa/500/195.png',
    'Ohio Bobcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/195.png',
    'Bowling Green': 'https://a.espncdn.com/i/teamlogos/ncaa/500/189.png',
    'Bowling Green Falcons': 'https://a.espncdn.com/i/teamlogos/ncaa/500/189.png',
    'Kent State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png',
    'Kent State Golden Flashes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png',
    'Toledo': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png',
    'Toledo Rockets': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png',
    'Eastern Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png',
    'Eastern Michigan Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png',
    'Western Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png',
    'Western Michigan Broncos': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png',
    'Central Michigan': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png',
    'Central Michigan Chippewas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png',
    'Northern Illinois': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png',
    'Northern Illinois Huskies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png',
    'Ball State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png',
    'Ball State Cardinals': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png',
    'Western Kentucky': 'https://a.espncdn.com/i/teamlogos/ncaa/500/98.png',
    'Western Kentucky Hilltoppers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/98.png',
    'Middle Tennessee': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
    'Middle Tennessee Blue Raiders': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
    'MTSU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png',
    'Marshall': 'https://a.espncdn.com/i/teamlogos/ncaa/500/276.png',
    'Marshall Thundering Herd': 'https://a.espncdn.com/i/teamlogos/ncaa/500/276.png',
    'Old Dominion': 'https://a.espncdn.com/i/teamlogos/ncaa/500/295.png',
    'Old Dominion Monarchs': 'https://a.espncdn.com/i/teamlogos/ncaa/500/295.png',
    'Appalachian State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
    'Appalachian State Mountaineers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png',
    'Coastal Carolina': 'https://a.espncdn.com/i/teamlogos/ncaa/500/324.png',
    'Coastal Carolina Chanticleers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/324.png',
    'Georgia Southern': 'https://a.espncdn.com/i/teamlogos/ncaa/500/290.png',
    'Georgia Southern Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/290.png',
    'Georgia State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
    'Georgia State Panthers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2247.png',
    'James Madison': 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png',
    'James Madison Dukes': 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png',
    'JMU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png',
    'Louisiana': 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    'Louisiana Ragin Cajuns': 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    'ULL': 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    'Louisiana Lafayette': 'https://a.espncdn.com/i/teamlogos/ncaa/500/309.png',
    'Louisiana Monroe': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png',
    'Louisiana Monroe Warhawks': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png',
    'ULM': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png',
    'South Alabama': 'https://a.espncdn.com/i/teamlogos/ncaa/500/6.png',
    'South Alabama Jaguars': 'https://a.espncdn.com/i/teamlogos/ncaa/500/6.png',
    'Southern Miss': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png',
    'Southern Mississippi Golden Eagles': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png',
    'Troy': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
    'Troy Trojans': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png',
    'Arkansas State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png',
    'Arkansas State Red Wolves': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png',
    'Texas State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/326.png',
    'Texas State Bobcats': 'https://a.espncdn.com/i/teamlogos/ncaa/500/326.png',
    'UTSA': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png',
    'UTSA Roadrunners': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png',
    'North Texas': 'https://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
    'North Texas Mean Green': 'https://a.espncdn.com/i/teamlogos/ncaa/500/249.png',
    'Rice': 'https://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
    'Rice Owls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/242.png',
    'UTEP': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png',
    'UTEP Miners': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png',
    'Florida Atlantic': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png',
    'Florida Atlantic Owls': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png',
    'FAU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png',
    'Florida International': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png',
    'FIU Panthers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png',
    'FIU': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png',
    'Charlotte': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png',
    'Charlotte 49ers': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png',
    'Liberty': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png',
    'Liberty Flames': 'https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png',
    'New Mexico State': 'https://a.espncdn.com/i/teamlogos/ncaa/500/166.png',
    'New Mexico State Aggies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/166.png',
    'Connecticut': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'UConn Huskies': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'UConn': 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    'UMass': 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png',
    'Massachusetts Minutemen': 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png'
  };

  // Try exact match first
  if (teamLogos[teamName]) {
    return teamLogos[teamName];
  }

  // Try matching with strict rules to avoid state school conflicts
  const foundKey = Object.keys(teamLogos).find(key => {
    const lowerTeam = teamName.toLowerCase();
    const lowerKey = key.toLowerCase();

    // Exact match check (case insensitive)
    if (lowerTeam === lowerKey) return true;

    // Split into words to check if it's a prefix match
    const teamWords = lowerTeam.split(' ');
    const keyWords = lowerKey.split(' ');

    // Multi-word keys require exact match (e.g., "Ohio State" won't match "Ohio")
    if (keyWords.length > 1) {
      return lowerTeam === lowerKey;
    }

    // Single word keys can match if team name STARTS with that word
    // This allows "Illinois" to match "Illinois Fighting Illini"
    // But NOT "Northern Illinois" (which starts with "Northern")
    if (keyWords.length === 1) {
      const singleKey = keyWords[0];

      // First word must match exactly
      if (teamWords[0] === singleKey) {
        return true;
      }
    }

    return false;
  });

  if (foundKey) {
    return teamLogos[foundKey];
  }

  // If no logo found, try to generate ESPN CDN URL by searching common team IDs
  // This is a fallback that attempts to find the logo dynamically
  return generateESPNLogoURL(teamName);
};

// Helper function to generate ESPN logo URL for teams not in the database
const generateESPNLogoURL = (teamName) => {
  // Clean up the team name
  const cleanName = teamName.replace(/\s+(Aggies|Bears|Bearcats|Beavers|Bengals|Billikens|Blazers|Blue Devils|Bobcats|Boilermakers|Broncos|Bruins|Buckeyes|Buffaloes|Bulldogs|Bulls|Cardinals|Catamounts|Cavaliers|Chanticleers|Chippewas|Commodores|Cornhuskers|Cougars|Cowboys|Crimson Tide|Cyclones|Demon Deacons|Devils|Ducks|Dukes|Eagles|Falcons|Fighting Irish|Flames|Gators|Golden Bears|Golden Eagles|Golden Flashes|Golden Gophers|Golden Hurricane|Gobblers|Green Wave|Grizzlies|Hawkeyes|Hilltoppers|Hokies|Hoosiers|Horned Frogs|Huskies|Hurricanes|Illini|Jaguars|Jayhawks|Knights|Lobos|Longhorns|Mean Green|Midshipmen|Minutemen|Monarchs|Mountaineers|Mustangs|Nittany Lions|Orange|Owls|Panthers|Patriots|Phoenix|Pirates|Ragin Cajuns|Rainbow Warriors|Rams|Ramblers|Razorbacks|Rebel Black Bears|Rebels|Red Raiders|Red Storm|Red Wolves|RedHawks|Roadrunners|Rockets|Scarlet Knights|Seminoles|Shockers|Sooners|Spartans|Sun Devils|Tar Heels|Terrapins|Thundering Herd|Tigers|Titans|Trojans|Utes|Vandals|Volunteers|Warhawks|Wildcats|Wolf Pack|Wolfpack|Wolverines|Yellow Jackets|Zips|49ers)$/i, '').trim();

  // Common ESPN team IDs mapping
  const espnTeamIds = {
    'Abilene Christian': '2000',
    'Air Force': '2005',
    'Akron': '2006',
    'Alabama': '333',
    'Alabama A&M': '2010',
    'Alabama State': '2011',
    'Albany': '399',
    'Alcorn State': '2016',
    'Appalachian State': '2026',
    'Arizona': '12',
    'Arizona State': '9',
    'Arkansas': '8',
    'Arkansas State': '2032',
    'Army': '349',
    'Auburn': '2',
    'Austin Peay': '2029',
    'Ball State': '2050',
    'Baylor': '239',
    'Bethune-Cookman': '2065',
    'Boise State': '68',
    'Boston College': '103',
    'Bowling Green': '189',
    'BYU': '252',
    'Buffalo': '2084',
    'Butler': '2086',
    'Cal Poly': '13',
    'California': '25',
    'Campbell': '2097',
    'Central Arkansas': '2110',
    'Central Connecticut': '2115',
    'Central Florida': '2116',
    'Central Michigan': '2117',
    'Charleston Southern': '2127',
    'Charlotte': '2429',
    'Chattanooga': '236',
    'Cincinnati': '2132',
    'Citadel': '2143',
    'Clemson': '228',
    'Coastal Carolina': '324',
    'Colgate': '2142',
    'Colorado': '38',
    'Colorado State': '36',
    'Columbia': '171',
    'Connecticut': '41',
    'Cornell': '172',
    'Dartmouth': '159',
    'Davidson': '2166',
    'Dayton': '2168',
    'Delaware': '48',
    'Delaware State': '2169',
    'Drake': '2181',
    'Duke': '150',
    'Duquesne': '2184',
    'East Carolina': '151',
    'East Tennessee State': '2197',
    'Eastern Illinois': '2198',
    'Eastern Kentucky': '2198',
    'Eastern Michigan': '2199',
    'Eastern Washington': '331',
    'Elon': '2210',
    'Florida': '57',
    'Florida A&M': '50',
    'Florida Atlantic': '2226',
    'Florida International': '2229',
    'Florida State': '52',
    'Fordham': '2230',
    'Fresno State': '278',
    'Furman': '231',
    'Gardner-Webb': '2241',
    'Georgia': '61',
    'Georgia Southern': '290',
    'Georgia State': '2247',
    'Georgia Tech': '59',
    'Grambling': '2755',
    'Hampton': '2261',
    'Harvard': '108',
    'Hawaii': '62',
    'Holy Cross': '107',
    'Houston': '248',
    'Houston Baptist': '2271',
    'Howard': '47',
    'Idaho': '70',
    'Idaho State': '304',
    'Illinois': '356',
    'Illinois State': '2287',
    'Incarnate Word': '2916',
    'Indiana': '84',
    'Indiana State': '282',
    'Iona': '314',
    'Iowa': '2294',
    'Iowa State': '66',
    'Jackson State': '2296',
    'Jacksonville': '294',
    'Jacksonville State': '55',
    'James Madison': '256',
    'Kansas': '2305',
    'Kansas State': '2306',
    'Kennesaw State': '338',
    'Kent State': '2309',
    'Kentucky': '96',
    'Lafayette': '322',
    'Lamar': '2320',
    'Lehigh': '2329',
    'Liberty': '2335',
    'Louisiana': '309',
    'Louisiana Monroe': '2433',
    'Louisiana Tech': '2348',
    'Louisville': '97',
    'LSU': '99',
    'Maine': '311',
    'Marshall': '276',
    'Maryland': '120',
    'Massachusetts': '113',
    'McNeese': '2377',
    'Memphis': '235',
    'Mercer': '2382',
    'Miami': '2390',
    'Miami (OH)': '193',
    'Michigan': '130',
    'Michigan State': '127',
    'Middle Tennessee': '2393',
    'Minnesota': '135',
    'Mississippi': '145',
    'Mississippi State': '344',
    'Missouri': '142',
    'Missouri State': '2623',
    'Monmouth': '2405',
    'Montana': '149',
    'Montana State': '147',
    'Morehead State': '2413',
    'Morgan State': '2415',
    'Murray State': '93',
    'Navy': '2426',
    'Nebraska': '158',
    'Nevada': '2440',
    'New Hampshire': '160',
    'New Mexico': '167',
    'New Mexico State': '166',
    'Nicholls': '2447',
    'NIU': '2459',
    'Norfolk State': '2452',
    'North Alabama': '6',
    'North Carolina': '153',
    'North Carolina A&T': '2448',
    'North Carolina Central': '2428',
    'North Dakota': '155',
    'North Dakota State': '2449',
    'North Texas': '249',
    'Northeastern': '111',
    'Northern Arizona': '2464',
    'Northern Colorado': '2458',
    'Northern Illinois': '2459',
    'Northern Iowa': '2460',
    'Northwestern': '77',
    'Northwestern State': '2466',
    'Notre Dame': '87',
    'Ohio': '195',
    'Ohio State': '194',
    'Oklahoma': '201',
    'Oklahoma State': '197',
    'Old Dominion': '295',
    'Ole Miss': '145',
    'Oregon': '2483',
    'Oregon State': '204',
    'Penn': '219',
    'Penn State': '213',
    'Pittsburgh': '221',
    'Portland State': '2501',
    'Prairie View A&M': '2504',
    'Presbyterian': '2506',
    'Princeton': '163',
    'Purdue': '2509',
    'Rhode Island': '227',
    'Rice': '242',
    'Richmond': '257',
    'Robert Morris': '2520',
    'Rutgers': '164',
    'Sacramento State': '16',
    'Sacred Heart': '2529',
    'Sam Houston': '2534',
    'Samford': '2535',
    'San Diego': '301',
    'San Diego State': '21',
    'San Jose State': '23',
    'Savannah State': '2545',
    'South Alabama': '6',
    'South Carolina': '2579',
    'South Carolina State': '2569',
    'South Dakota': '233',
    'South Dakota State': '2571',
    'South Florida': '58',
    'Southeast Missouri State': '2546',
    'Southeastern Louisiana': '2545',
    'Southern': '2582',
    'Southern Illinois': '79',
    'Southern Miss': '2572',
    'Southern Utah': '253',
    'St. Francis': '2598',
    'Stanford': '24',
    'Stephen F. Austin': '2617',
    'Stetson': '526',
    'Stony Brook': '2619',
    'Syracuse': '183',
    'TCU': '2628',
    'Temple': '218',
    'Tennessee': '2633',
    'Tennessee State': '2634',
    'Tennessee Tech': '2635',
    'Texas': '251',
    'Texas A&M': '245',
    'Texas Southern': '2640',
    'Texas State': '326',
    'Texas Tech': '2641',
    'The Citadel': '2643',
    'Toledo': '2649',
    'Towson': '119',
    'Troy': '2653',
    'Tulane': '2655',
    'Tulsa': '202',
    'UAB': '5',
    'UCF': '2116',
    'UCLA': '26',
    'UConn': '41',
    'UMass': '113',
    'UNC': '153',
    'UNLV': '2439',
    'USC': '30',
    'UT Martin': '2630',
    'UTEP': '2638',
    'UTSA': '2636',
    'Utah': '254',
    'Utah State': '328',
    'Valparaiso': '2674',
    'Vanderbilt': '238',
    'Villanova': '222',
    'Virginia': '258',
    'Virginia Tech': '259',
    'VMI': '2681',
    'Wagner': '2692',
    'Wake Forest': '154',
    'Washington': '264',
    'Washington State': '265',
    'Weber State': '2692',
    'West Virginia': '277',
    'Western Carolina': '2717',
    'Western Illinois': '2710',
    'Western Kentucky': '98',
    'Western Michigan': '2711',
    'William & Mary': '2729',
    'Wofford': '2747',
    'Wyoming': '2840',
    'Yale': '43',
    'Youngstown State': '2894'
  };

  // Look up the team ID
  const teamId = espnTeamIds[cleanName] || espnTeamIds[teamName];

  if (teamId) {
    console.log(`🔍 Found logo for ${teamName} (ID: ${teamId})`);
    return `https://a.espncdn.com/i/teamlogos/ncaa/500/${teamId}.png`;
  }

  console.warn(`⚠️ No logo found for team: ${teamName}`);
  return '';
};

export const getCFBTeamShortName = (teamName) => {
  const shortNames = {
    'Oregon': 'ORE',
    'Oregon Ducks': 'ORE',
    'Georgia': 'UGA',
    'Georgia Bulldogs': 'UGA',
    'Ohio State': 'OSU',
    'Ohio State Buckeyes': 'OSU',
    'Penn State': 'PSU',
    'Penn State Nittany Lions': 'PSU',
    'Texas': 'TEX',
    'Texas Longhorns': 'TEX',
    'Miami': 'MIA',
    'Miami Hurricanes': 'MIA',
    'Alabama': 'ALA',
    'Alabama Crimson Tide': 'ALA',
    'Ole Miss': 'MISS',
    'Ole Miss Rebels': 'MISS',
    'Mississippi': 'MISS',
    'Tennessee': 'TENN',
    'Tennessee Volunteers': 'TENN',
    'LSU': 'LSU',
    'LSU Tigers': 'LSU',
    'Clemson': 'CLEM',
    'Clemson Tigers': 'CLEM',
    'Iowa State': 'ISU',
    'Iowa State Cyclones': 'ISU',
    'BYU': 'BYU',
    'BYU Cougars': 'BYU',
    'Notre Dame': 'ND',
    'Notre Dame Fighting Irish': 'ND',
    'Texas A&M': 'TAMU',
    'Texas A&M Aggies': 'TAMU',
    'Kansas State': 'KSU',
    'Kansas State Wildcats': 'KSU',
    'Oklahoma': 'OU',
    'Oklahoma Sooners': 'OU',
    'USC': 'USC',
    'USC Trojans': 'USC',
    'Southern California': 'USC',
    'Michigan': 'MICH',
    'Michigan Wolverines': 'MICH',
    'SMU': 'SMU',
    'SMU Mustangs': 'SMU',
    'Louisville': 'LOU',
    'Louisville Cardinals': 'LOU',
    'Missouri': 'MIZ',
    'Missouri Tigers': 'MIZ',
    'Illinois': 'ILL',
    'Illinois Fighting Illini': 'ILL',
    'Boise State': 'BSU',
    'Boise State Broncos': 'BSU',
    'Washington': 'WASH',
    'Washington Huskies': 'WASH',
    'Memphis': 'MEM',
    'Memphis Tigers': 'MEM',
    'South Florida': 'USF',
    'South Florida Bulls': 'USF',
    'USF': 'USF',
    'Florida State': 'FSU',
    'Florida State Seminoles': 'FSU',
    'FSU': 'FSU',
    'Georgia Tech': 'GT',
    'Georgia Tech Yellow Jackets': 'GT',
    'Arizona State': 'ASU',
    'Arizona State Sun Devils': 'ASU',
    'Houston': 'HOU',
    'Houston Cougars': 'HOU',
    'Akron': 'AKR',
    'Akron Zips': 'AKR',
    'Cincinnati': 'CIN',
    'Cincinnati Bearcats': 'CIN',
    'UCF': 'UCF',
    'UCF Knights': 'UCF',
    'Central Florida': 'UCF',
    'Tulane': 'TUL',
    'Tulane Green Wave': 'TUL',
    'Navy': 'NAVY',
    'Navy Midshipmen': 'NAVY',
    'Army': 'ARMY',
    'Army Black Knights': 'ARMY',
    'UNLV': 'UNLV',
    'UNLV Rebels': 'UNLV',
    'Liberty': 'LIB',
    'Liberty Flames': 'LIB',
    'James Madison': 'JMU',
    'James Madison Dukes': 'JMU',
    'JMU': 'JMU',
    'Appalachian State': 'APP',
    'Appalachian State Mountaineers': 'APP',
    'Coastal Carolina': 'CCU',
    'Coastal Carolina Chanticleers': 'CCU'
  };

  // Try exact match first
  if (shortNames[teamName]) {
    return shortNames[teamName];
  }

  // Try partial match
  const foundKey = Object.keys(shortNames).find(key =>
    teamName.toLowerCase().includes(key.toLowerCase()) ||
    key.toLowerCase().includes(teamName.toLowerCase())
  );

  return foundKey ? shortNames[foundKey] : teamName.substring(0, 4).toUpperCase();
};
