// MLB ML Predictions Utility
// Loads model output from mlb_ml_predictions.json (generated by ml_mlb/mlb_predict_upcoming.py)
// and combines it with the market the way ml_mlb/mlb_evaluate_blend.py found most accurate
import predictionFile from '../mlb_ml_predictions.json';
import { americanToImplied } from './oddsCalculations';

export const MLB_MODEL_INFO = {
  generatedAt: predictionFile.generated_at ? new Date(predictionFile.generated_at) : null,
  metrics: predictionFile.model || {},
  blend: predictionFile.blend || null,
  gameCount: predictionFile.games?.length || 0
};

const MATCH_WINDOW_MS = 12 * 60 * 60 * 1000;

/**
 * Find the model prediction for an Odds API game (same teams, closest start time)
 */
export const findMLBPrediction = (game) => {
  const start = new Date(game.commence_time).getTime();
  let best = null;
  (predictionFile.games || []).forEach(p => {
    if (p.home_team !== game.home_team || p.away_team !== game.away_team) return;
    const gap = Math.abs(new Date(p.game_datetime).getTime() - start);
    if (gap <= MATCH_WINDOW_MS && (!best || gap < best.gap)) best = { pred: p, gap };
  });
  return best?.pred || null;
};

// Most common line across books (e.g. -1.5 run line, 8.5 total)
const consensusPoint = (bookmakers, marketKey, outcomeName) => {
  const counts = {};
  bookmakers.forEach(book => {
    const outcome = book.markets?.find(m => m.key === marketKey)?.outcomes?.find(o => o.name === outcomeName);
    if (outcome?.point !== undefined) counts[outcome.point] = (counts[outcome.point] || 0) + 1;
  });
  const entries = Object.entries(counts);
  if (!entries.length) return null;
  return parseFloat(entries.sort((a, b) => b[1] - a[1] || Math.abs(a[0]) - Math.abs(b[0]))[0][0]);
};

// Best price for an outcome, optionally only at a specific line
const bestPrice = (bookmakers, marketKey, outcomeName, point = null) => {
  let best = null;
  bookmakers.forEach(book => {
    const outcome = book.markets?.find(m => m.key === marketKey)?.outcomes?.find(o => o.name === outcomeName);
    if (!outcome) return;
    if (point !== null && outcome.point !== point) return;
    if (!best || outcome.price > best.odds) {
      best = { bookmaker: book.title, odds: outcome.price, points: outcome.point ?? null };
    }
  });
  return best;
};

/**
 * Best available prices for a game. Run line and total are priced at the consensus line
 * so both sides (and the model probability) always refer to the same line.
 */
export const getMLBGameLines = (game, selectedBookmakers = []) => {
  const books = selectedBookmakers.length
    ? game.bookmakers.filter(b => selectedBookmakers.includes(b.title))
    : game.bookmakers;
  const { home_team: home, away_team: away } = game;
  const homeRL = consensusPoint(books, 'spreads', home);
  const totalLine = consensusPoint(books, 'totals', 'Over');
  return {
    homeML: bestPrice(books, 'h2h', home),
    awayML: bestPrice(books, 'h2h', away),
    homeSpread: homeRL === null ? null : bestPrice(books, 'spreads', home, homeRL),
    awaySpread: homeRL === null ? null : bestPrice(books, 'spreads', away, -homeRL),
    over: totalLine === null ? null : bestPrice(books, 'totals', 'Over', totalLine),
    under: totalLine === null ? null : bestPrice(books, 'totals', 'Under', totalLine)
  };
};

// Consensus (median) no-vig probability of side A across every book offering this exact line
const marketNoVig = (bookmakers, marketKey, nameA, nameB, pointA = null) => {
  const probs = [];
  bookmakers.forEach(book => {
    const outcomes = book.markets?.find(m => m.key === marketKey)?.outcomes || [];
    // Opposite side: same total for over/under, mirrored line for the run line
    const pointB = pointA === null ? null : marketKey === 'totals' ? pointA : -pointA;
    const a = outcomes.find(o => o.name === nameA && (pointA === null || o.point === pointA));
    const b = outcomes.find(o => o.name === nameB && (pointB === null || o.point === pointB));
    if (!a || !b) return;
    const ia = americanToImplied(a.price);
    const ib = americanToImplied(b.price);
    probs.push((ia / (ia + ib)) * 100);
  });
  if (!probs.length) return null;
  probs.sort((x, y) => x - y);
  const mid = Math.floor(probs.length / 2);
  return probs.length % 2 ? probs[mid] : (probs[mid - 1] + probs[mid]) / 2;
};

/**
 * Market consensus no-vig probabilities (percent) at the consensus lines
 */
export const marketMLBProbabilities = (game, lines = getMLBGameLines(game)) => {
  const { home_team: home, away_team: away, bookmakers } = game;
  const mlHome = marketNoVig(bookmakers, 'h2h', home, away);
  const rlHome = lines.homeSpread ? marketNoVig(bookmakers, 'spreads', home, away, lines.homeSpread.points) : null;
  const over = lines.over ? marketNoVig(bookmakers, 'totals', 'Over', 'Under', lines.over.points) : null;
  return {
    mlHome, mlAway: mlHome === null ? null : 100 - mlHome,
    rlHome, rlAway: rlHome === null ? null : 100 - rlHome,
    over, under: over === null ? null : 100 - over
  };
};

/**
 * Prediction inputs in the format the MLB page uses, from market odds alone
 */
export const impliedMLBProbabilities = (game, lines = getMLBGameLines(game)) => {
  const m = marketMLBProbabilities(game, lines);
  const { home_team: home, away_team: away } = game;
  const out = {};
  if (m.mlHome !== null) [out[`${home}_ml`], out[`${away}_ml`]] = [m.mlHome.toFixed(1), m.mlAway.toFixed(1)];
  if (m.rlHome !== null) [out[`${home}_spread`], out[`${away}_spread`]] = [m.rlHome.toFixed(1), m.rlAway.toFixed(1)];
  if (m.over !== null) [out.over, out.under] = [m.over.toFixed(1), m.under.toFixed(1)];
  return out;
};

const logit = (pct) => {
  const p = Math.min(Math.max(pct / 100, 1e-4), 1 - 1e-4);
  return Math.log(p / (1 - p));
};

/**
 * Combine model and market as chosen by the backtest (model / market / blend)
 */
const combine = (kind, modelPct, marketPct) => {
  const cfg = MLB_MODEL_INFO.blend?.[kind];
  if (modelPct === null || modelPct === undefined) return marketPct;
  if (!cfg || marketPct === null || marketPct === undefined) return modelPct;
  if (cfg.method === 'market') return marketPct;
  if (cfg.method === 'model') return modelPct;
  const z = cfg.model_coef * logit(modelPct) + cfg.market_coef * logit(marketPct) + cfg.intercept;
  return 100 / (1 + Math.exp(-z));
};

const round1 = (v) => (v === null || v === undefined ? null : Math.round(v * 10) / 10);

/**
 * Final probabilities (percent) for the lines the books are offering, plus the raw
 * model and market numbers they came from. Totals exclude pushes (win-or-lose odds).
 */
export const computeMLBProbabilities = (pred, game, lines = getMLBGameLines(game)) => {
  const market = marketMLBProbabilities(game, lines);

  // Raw model numbers
  const model = { mlHome: pred.home_win_prob, rlHome: null, over: null, push: 0 };
  const homePoint = lines.homeSpread?.points;
  if (homePoint !== null && homePoint !== undefined) {
    // (margin keys are half-runs like "1.5" / "-1.5", matching Python's str(float))
    model.rlHome = pred.home_margin_probs?.[String(-homePoint)] ?? null;
  }
  const totalPoint = lines.over?.points;
  if (totalPoint !== null && totalPoint !== undefined) {
    const t = pred.total_probs?.[Number.isInteger(totalPoint) ? `${totalPoint}.0` : String(totalPoint)];
    if (t) {
      model.over = (t.over / (t.over + t.under)) * 100;
      model.push = round1(100 - t.over - t.under);
    }
  }

  // Final: moneyline + totals per the backtest. The run line uses the market's own run line
  // when the market won; otherwise it follows the final win probability via the model's margin table
  const mlMethod = MLB_MODEL_INFO.blend?.moneyline?.method || 'model';
  const mlHome = combine('moneyline', model.mlHome, market.mlHome);
  let rlHome = model.rlHome;
  if (mlMethod === 'market' && market.rlHome !== null) {
    rlHome = market.rlHome;
  } else if (homePoint !== null && homePoint !== undefined && mlHome !== null) {
    const table = predictionFile.margin_by_win_prob?.[String(Math.min(99, Math.max(1, Math.round(mlHome))))];
    rlHome = table?.[String(-homePoint)] ?? rlHome;
  }
  const over = combine('totals', model.over, market.over);

  return {
    mlHome: round1(mlHome), mlAway: mlHome === null ? null : round1(100 - mlHome),
    rlHome: round1(rlHome), rlAway: rlHome === null ? null : round1(100 - rlHome),
    over: round1(over), under: over === null ? null : round1(100 - over),
    push: model.push,
    model: {
      mlHome: model.mlHome, mlAway: round1(100 - model.mlHome),
      rlHome: model.rlHome, rlAway: model.rlHome === null ? null : round1(100 - model.rlHome),
      over: round1(model.over), under: model.over === null ? null : round1(100 - model.over)
    },
    market
  };
};

/**
 * Build the prediction inputs the MLB page uses (same keys as the other sport pages)
 */
export const loadMLBMLPredictions = (games) => {
  const predictions = {};
  games.forEach(game => {
    const pred = findMLBPrediction(game);
    if (!pred) return;
    const p = computeMLBProbabilities(pred, game);
    const { home_team: home, away_team: away } = game;

    const entry = { _hasMLPredictions: true, _projection: pred, _probabilities: p };
    if (p.mlHome !== null) {
      entry[`${home}_ml`] = p.mlHome.toFixed(1);
      entry[`${away}_ml`] = p.mlAway.toFixed(1);
    }
    if (p.rlHome !== null) {
      entry[`${home}_spread`] = p.rlHome.toFixed(1);
      entry[`${away}_spread`] = p.rlAway.toFixed(1);
    }
    if (p.over !== null) {
      entry.over = p.over.toFixed(1);
      entry.under = p.under.toFixed(1);
    }
    predictions[game.id] = entry;
  });
  console.log(`🤖 MLB model predictions matched: ${Object.keys(predictions).length}/${games.length}`);
  return predictions;
};
